export const ADD_CITY_WEATHER = "ADD_CITY_WEATHER"
export const DELETE_CITY_WEATHER = "DELETE_CITY_WEATHER"
export const UPDATE_CITY_WEATHER = "UPDATE_CITY_WEATHER"
export const UPDATE_SEARCH_WEATHER = "UPDATE_SEARCH_WEATHER"